# Generated by Django 4.1.1 on 2022-09-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('idAuxiliar', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('create_date', models.DateField(verbose_name='Create date')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellidos')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(verbose_name='create_date')),
                ('direccion', models.CharField(max_length=50, verbose_name='residencia')),
                ('ciudad', models.CharField(max_length=20, verbose_name='ciudad')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_auxiliar_registro_paciente', to='hospitalApp.auxiliar')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_paciente', to='hospitalApp.usuario', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='auxiliar',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_auxiliar', to='hospitalApp.usuario', unique=True),
        ),
    ]
